package com.phigey.bootme.dao.mapper;

import com.phigey.bootme.dao.entity.Diary;
import org.apache.ibatis.annotations.Mapper;

/**
 * @author hanyu
 */
@Mapper
public interface DiaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insert(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insertSelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    Diary selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKeySelective(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Diary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_diary
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKey(Diary record);
}