package com.phigey.bootme.dao.mapper;

import com.phigey.bootme.dao.entity.Province;
import org.apache.ibatis.annotations.Mapper;

/**
 * @author hanyu
 */
@Mapper
public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    Province selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_province
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKey(Province record);
}