package com.phigey.bootme.dao.mapper;

import com.phigey.bootme.dao.entity.Tag;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insert(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int insertSelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    Tag selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKeySelective(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_tag
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    int updateByPrimaryKey(Tag record);
}