global:
  queue:
    cmd: quque_cmd
    result: queue_result

  daemon:
    host: phigey.com
spring:
  profiles:
    active: dev
  liquibase:
    enabled: true
  devtools:
    restart:
      enabled: false

management:
  health:
    redis:
      enabled: true
    db:
      enabled: true
    rabbit:
      enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    lazy-loading-enabled: true

logging:
  level:
    root: INFO

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${global.daemon.host}:30106/db03?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: fish
    password: fish
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: ${global.daemon.host}
    port: 50079
    password: 123456
    timeout: 60
    database: 0

  rabbitmq:
    host: ${global.daemon.host}
    port: 50072
    username: sheep
    password: sheep
    virtual-host: /


server:
  port: 9095

socket.io:
  host: localhost
  port: 9096

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${global.daemon.host}:30106/db03?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: fish
    password: fish
    driver-class-name: com.mysql.jdbc.Driver

  redis:
    host: ${global.daemon.host}
    port: 50079
    password: 123456
    timeout: 60
    database: 0

  rabbitmq:
    host: ${global.daemon.host}
    port: 50072
    username: sheep
    password: sheep


server:
  port: 9097

socket.io:
  host: localhost
  port: 9098



