spring:
  profiles:
    active: prod

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.7.8:30106/db03?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: fish
    password: fish
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
  devtools:
    restart:
      enabled: false

server:
  port: 9095

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: INFO

#### websocket properties
socket.io:
  host: localhost
  port: 9096

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.7.8:30106/db03?useSSL=false&useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
    username: fish
    password: fish
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: true
  devtools:
    restart:
      enabled: false
server:
  port: 9097

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: INFO

#### websocket properties
socket.io:
  host: localhost
  port: 9098



