package com.phigey.bootme.dao.entity;

import java.io.Serializable;

/**
 * @author hanyu
 */
public class City implements Serializable {
    private static final long serialVersionUID = 4120177860088801992L;

    private String code;

    private String name;

    private String provinceCode;

    public City() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.code
     *
     * @return the value of tb_city.code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.code
     *
     * @param code the value for tb_city.code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.name
     *
     * @return the value of tb_city.name
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.name
     *
     * @param name the value for tb_city.name
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_city.province_code
     *
     * @return the value of tb_city.province_code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getProvinceCode() {
        return provinceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_city.province_code
     *
     * @param provinceCode the value for tb_city.province_code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setProvinceCode(String provinceCode) {
        this.provinceCode = provinceCode == null ? null : provinceCode.trim();
    }
}