package com.phigey.bootme.dao.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @author hanyu
 */
public class Diary implements Serializable {
    private static final long serialVersionUID = 6768678075575052751L;

    private Long id;

    private String title;

    private Long userId;

    private Integer openType;

    private Date createTime;

    private Date updateTime;

    private String source;

    public Diary() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.id
     *
     * @return the value of tb_diary.id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.id
     *
     * @param id the value for tb_diary.id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.title
     *
     * @return the value of tb_diary.title
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.title
     *
     * @param title the value for tb_diary.title
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.user_id
     *
     * @return the value of tb_diary.user_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.user_id
     *
     * @param userId the value for tb_diary.user_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.open_type
     *
     * @return the value of tb_diary.open_type
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Integer getOpenType() {
        return openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.open_type
     *
     * @param openType the value for tb_diary.open_type
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setOpenType(Integer openType) {
        this.openType = openType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.create_time
     *
     * @return the value of tb_diary.create_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.create_time
     *
     * @param createTime the value for tb_diary.create_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.update_time
     *
     * @return the value of tb_diary.update_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.update_time
     *
     * @param updateTime the value for tb_diary.update_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_diary.source
     *
     * @return the value of tb_diary.source
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_diary.source
     *
     * @param source the value for tb_diary.source
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
}