package com.phigey.bootme.dao.entity;

import java.io.Serializable;

/**
 * @author hanyu
 */
public class Province implements Serializable {

    private static final long serialVersionUID = -8566509893535960883L;

    private String code;

    private String name;

    public Province() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.code
     *
     * @return the value of tb_province.code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_province.code
     *
     * @param code the value for tb_province.code
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_province.name
     *
     * @return the value of tb_province.name
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_province.name
     *
     * @param name the value for tb_province.name
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}