package com.phigey.bootme.dao.entity;

import java.io.Serializable;
import java.util.Date;

/**
 * @author cfa
 */
public class TagMap implements Serializable {

    private static final long serialVersionUID = -8409785018889650566L;
    private Long id;

    private Long mapId;

    private Long tagId;

    private Date createTime;

    public TagMap() {
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag_map.id
     *
     * @return the value of tb_tag_map.id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag_map.id
     *
     * @param id the value for tb_tag_map.id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag_map.map_id
     *
     * @return the value of tb_tag_map.map_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Long getMapId() {
        return mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag_map.map_id
     *
     * @param mapId the value for tb_tag_map.map_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setMapId(Long mapId) {
        this.mapId = mapId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag_map.tag_id
     *
     * @return the value of tb_tag_map.tag_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Long getTagId() {
        return tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag_map.tag_id
     *
     * @param tagId the value for tb_tag_map.tag_id
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setTagId(Long tagId) {
        this.tagId = tagId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_tag_map.create_time
     *
     * @return the value of tb_tag_map.create_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_tag_map.create_time
     *
     * @param createTime the value for tb_tag_map.create_time
     *
     * @mbg.generated Sun Mar 08 15:04:18 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}